DEFAULT_LOCALE = "en"
SUPPORTED_LOCALES = ("en", "ru")

TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "common.server_only": "This command can only be used in a server.",
        "common.api_missing": "BOT_API_URL is not configured.",
        "common.target_self": "You cannot use this command on yourself.",
        "common.target_owner": "You cannot moderate the server owner.",
        "common.target_hierarchy": "You cannot moderate a member with equal or higher role.",
        "common.target_bot_hierarchy": "I cannot moderate this member due to role hierarchy.",
        "common.not_configured": "Not configured",
        "common.rule_fallback": "Rule",
        "common.bool_true": "Yes",
        "common.bool_false": "No",
        "common.manual_unmute_reason": "Manual unmute",
        "warn.fetch_rules_failed": "Could not fetch moderation rules from API: {error}",
        "warn.invalid_rule": "Selected rule is invalid or no longer active. Please choose from autocomplete suggestions.",
        "warn.dm_failed_privacy": "Cannot DM this user (privacy settings), but the warning will still be logged.",
        "warn.dm_failed_generic": "Could not send DM due to Discord API error ({status}), but the warning will still be logged.",
        "warn.dm_failed_forbidden": "Could not send a DM to the user, but the warning will still be logged.",
        "warn.api_missing": "BOT_API_URL is not configured.",
        "warn.success": "Successfully warned {mention} for `{rule}` and logged the action.",
        "warn.api_request_error": "An error occurred while communicating with the API: {error}",
        "warn.api_http_error": "The API responded with an error: {status} - {text}",
        "warn.dm_body": "You have been warned in **{server_name}** for the following rule:\n> {rule_label}",
        "warn.dm_commentary": "\n\nModerator commentary:\n> {commentary}",
        "settings.show_title": "Moderation settings:",
        "settings.mute_role": "- Mute role: `{value}`",
        "settings.mod_log_channel": "- Mod log channel: {value}",
        "settings.language": "- Language: `{value}`",
        "settings.default_mute_minutes": "- Default mute minutes: `{value}`",
        "settings.max_mute_minutes": "- Max mute minutes: `{value}`",
        "settings.auto_reconnect": "- Voice reconnect on mute: `{value}`",
        "settings.log_channel_set": "Moderation log channel set to {mention}.",
        "settings.log_channel_cleared": "Moderation log channel cleared.",
        "settings.default_over_max": "Default minutes cannot be greater than max minutes.",
        "settings.defaults_updated": "Mute defaults updated: default={default_minutes}m, max={max_minutes}m, auto_reconnect={auto_reconnect}.",
        "settings.channel_not_found": "`{channel_id}` (not found)",
        "settings.mute_role_set": "Mute role set to `{role_name}`.",
        "settings.mute_role_created": "Created mute role `{role_name}` and updated `{edited}` channel overwrites (failed: {failed}).",
        "mute.fetch_rules_failed": "Could not fetch moderation rules: {error}",
        "mute.invalid_rule": "Invalid rule selected.",
        "mute.role_not_configured": "Mute role is not configured. Use `/moderation settings moderation_set_mute_role` or `/moderation settings moderation_create_mute_role`.",
        "mute.role_missing": "Configured mute role is missing on this server. Reconfigure it.",
        "mute.role_too_high": "I cannot assign this mute role because it is above or equal to my highest role.",
        "mute.duration_exceeds": "Duration exceeds server max mute time ({max_minutes} minutes).",
        "mute.assign_forbidden": "I do not have permission to assign the mute role.",
        "mute.assign_failed": "Failed to assign mute role: {error}",
        "mute.reconnect_ok": " Voice reconnect applied.",
        "mute.reconnect_failed": " Could not reconnect user in voice (check move permissions).",
        "mute.log_failed": "User muted, but logging action failed: {error}",
        "mute.success": "{mention} muted for `{duration}` minutes by rule `{rule}`.{note}",
        "unmute.remove_forbidden": "I do not have permission to remove the mute role.",
        "unmute.remove_failed": "Failed to remove mute role: {error}",
        "unmute.success": "{mention} unmuted. Removed role: `{removed_role}`. Closed active mute actions: `{deactivated}`.",
        "settings.language_updated": "Server language updated to `{locale}`.",
        "settings.language_not_supported": "Unsupported language. Supported: {supported}.",
        "rules.import_message_success": "Imported `{imported_count}` moderation rules from message `{message_id}`.",
        "rules.import_messages_success": "Imported `{imported_count}` moderation rules from `{message_count}` messages.",
        "rules.import_failed_http": "Import failed: {status} - {text}",
        "rules.import_failed_generic": "Import failed: {error}",
        "rules.invalid_message_link": "Invalid Discord message link format.",
        "rules.message_other_server": "That message is not from this server.",
        "rules.links_required": "Provide at least one Discord message link.",
        "rules.too_many_links": "Too many links. Maximum is 25 per command.",
        "rules.invalid_message_link_item": "Invalid message link: `{link}`",
        "rules.other_server_link_item": "Link is from another server: `{link}`",
        "rules.rule_added": "Rule added: `{label}`",
        "rules.rule_add_failed_http": "Failed to add rule: {status} - {text}",
        "rules.rule_add_failed_generic": "Failed to add rule: {error}",
        "rules.none_configured": "No active moderation rules configured.",
        "rules.active_header": "Active moderation rules:\n{body}",
        "rules.fetch_failed_http": "Failed to fetch rules: {status} - {text}",
        "rules.fetch_failed_generic": "Failed to fetch rules: {error}",
        "rules.guide_fetch_failed": "Failed to fetch guide: {error}",
        "rules.guide_empty": "No guide available.",
        "rules.guide_example": "Example:",
        "rules.manage_server_required": "You need Manage Server permission.",
        "security.verified_role_missing": "Verified role is not configured or not found on this server.",
        "security.verified_role_set": "Verified role set to \"{role_name}\".",
        "security.permissions_captured": "Captured current \"{role_name}\" permissions into `{mode}` template.",
        "security.template_missing": "No `{template_name}` permissions template configured yet. Use `/moderation security security_capture_permissions` first.",
        "security.lockdown_updated": "Lockdown {state}. Updated role `{role_name}` permissions from `{template_name}` template.",
        "security.verify_already_has": "{mention} already has `{role_name}`.",
        "security.verify_granted": "Granted `{role_name}` to {mention}.",
        "security.state_enabled": "enabled",
        "security.state_disabled": "disabled",
        "modlog.header": "[MODERATION LOG]",
        "modlog.action_label": "Action",
        "modlog.action_unmute": "unmute",
        "modlog.action_auto_unmute": "auto-unmute",
        "modlog.target_label": "Target",
        "modlog.moderator_label": "Moderator",
        "modlog.reason_label": "Reason",
        "modlog.removed_role_label": "Removed Mute Role",
        "modlog.closed_actions_label": "Closed Active Mutes",
        "modlog.logged_at_label": "Logged At",
        "modlog.unknown": "unknown",
        "modlog.reason_mute_expired": "Mute expired",
    },
    "ru": {
        "common.api_missing": "BOT_API_URL не настроен.",
        "common.not_configured": "Не настроено",
        "common.rule_fallback": "Правило",
        "common.bool_true": "Да",
        "common.bool_false": "Нет",
        "common.manual_unmute_reason": "Ручной размут",
        "settings.channel_not_found": "`{channel_id}` (не найден)",
        "settings.mute_role_set": "Роль мута установлена: `{role_name}`.",
        "settings.mute_role_created": "Создана роль мута `{role_name}` и обновлены права в `{edited}` каналах (ошибок: {failed}).",
        "rules.import_message_success": "Импортировано `{imported_count}` правил модерации из сообщения `{message_id}`.",
        "rules.import_messages_success": "Импортировано `{imported_count}` правил модерации из `{message_count}` сообщений.",
        "rules.import_failed_http": "Импорт не удался: {status} - {text}",
        "rules.import_failed_generic": "Импорт не удался: {error}",
        "rules.invalid_message_link": "Неверный формат ссылки на сообщение Discord.",
        "rules.message_other_server": "Это сообщение не из этого сервера.",
        "rules.links_required": "Укажите хотя бы одну ссылку на сообщение Discord.",
        "rules.too_many_links": "Слишком много ссылок. Максимум 25 за одну команду.",
        "rules.invalid_message_link_item": "Неверная ссылка на сообщение: `{link}`",
        "rules.other_server_link_item": "Ссылка ведёт на другой сервер: `{link}`",
        "rules.rule_added": "Правило добавлено: `{label}`",
        "rules.rule_add_failed_http": "Не удалось добавить правило: {status} - {text}",
        "rules.rule_add_failed_generic": "Не удалось добавить правило: {error}",
        "rules.none_configured": "Активные правила модерации не настроены.",
        "rules.active_header": "Активные правила модерации:\n{body}",
        "rules.fetch_failed_http": "Не удалось получить правила: {status} - {text}",
        "rules.fetch_failed_generic": "Не удалось получить правила: {error}",
        "rules.guide_fetch_failed": "Не удалось получить гайд: {error}",
        "rules.guide_empty": "Гайд недоступен.",
        "rules.guide_example": "Пример:",
        "rules.manage_server_required": "Нужно право Manage Server.",
        "security.verified_role_missing": "Роль verified не настроена или не найдена на этом сервере.",
        "security.verified_role_set": "Роль verified установлена: \"{role_name}\".",
        "security.permissions_captured": "Текущие права роли \"{role_name}\" сохранены в шаблон `{mode}`.",
        "security.template_missing": "Шаблон прав `{template_name}` ещё не настроен. Сначала выполните `/moderation security security_capture_permissions`.",
        "security.lockdown_updated": "Lockdown {state}. Права роли `{role_name}` обновлены из шаблона `{template_name}`.",
        "security.verify_already_has": "{mention} уже имеет `{role_name}`.",
        "security.verify_granted": "{mention} выдана роль `{role_name}`.",
        "security.state_enabled": "включен",
        "security.state_disabled": "выключен",
        "modlog.header": "[ЛОГ МОДЕРАЦИИ]",
        "modlog.action_label": "Действие",
        "modlog.action_unmute": "размут",
        "modlog.action_auto_unmute": "авто-размут",
        "modlog.target_label": "Цель",
        "modlog.moderator_label": "Модератор",
        "modlog.reason_label": "Причина",
        "modlog.removed_role_label": "Роль мута снята",
        "modlog.closed_actions_label": "Закрыто активных мутов",
        "modlog.logged_at_label": "Время лога",
        "modlog.unknown": "неизвестно",
        "modlog.reason_mute_expired": "Срок мута истёк",
        "common.server_only": "Эту команду можно использовать только на сервере.",
        "common.target_self": "Нельзя применять команду к самому себе.",
        "common.target_owner": "Нельзя модерировать владельца сервера.",
        "common.target_hierarchy": "Нельзя модерировать участника с равной или более высокой ролью.",
        "common.target_bot_hierarchy": "Я не могу модерировать этого участника из-за иерархии ролей.",
        "warn.fetch_rules_failed": "Не удалось получить правила модерации из API: {error}",
        "warn.invalid_rule": "Выбранное правило недействительно или больше не активно. Выберите правило из автодополнения.",
        "warn.dm_failed_privacy": "Не удалось отправить ЛС пользователю (настройки приватности), но предупреждение будет сохранено.",
        "warn.dm_failed_generic": "Не удалось отправить ЛС из-за ошибки Discord API ({status}), но предупреждение будет сохранено.",
        "warn.dm_failed_forbidden": "Не удалось отправить ЛС пользователю, но предупреждение будет сохранено.",
        "warn.api_missing": "BOT_API_URL не настроен.",
        "warn.success": "Пользователь {mention} успешно предупреждён по правилу `{rule}`, действие сохранено.",
        "warn.api_request_error": "Ошибка при обращении к API: {error}",
        "warn.api_http_error": "API вернул ошибку: {status} - {text}",
        "warn.dm_body": "Вы получили предупреждение на сервере **{server_name}** по правилу:\n> {rule_label}",
        "warn.dm_commentary": "\n\nКомментарий модератора:\n> {commentary}",
        "settings.show_title": "Настройки модерации:",
        "settings.mute_role": "- Роль мута: `{value}`",
        "settings.mod_log_channel": "- Канал мод-логов: {value}",
        "settings.language": "- Язык: `{value}`",
        "settings.default_mute_minutes": "- Мут по умолчанию (мин): `{value}`",
        "settings.max_mute_minutes": "- Максимальный мут (мин): `{value}`",
        "settings.auto_reconnect": "- Переподключение в войсе при муте: `{value}`",
        "settings.log_channel_set": "Канал мод-логов установлен: {mention}.",
        "settings.log_channel_cleared": "Канал мод-логов очищен.",
        "settings.default_over_max": "Значение по умолчанию не может быть больше максимального.",
        "settings.defaults_updated": "Параметры мута обновлены: default={default_minutes}м, max={max_minutes}м, auto_reconnect={auto_reconnect}.",
        "mute.fetch_rules_failed": "Не удалось получить правила модерации: {error}",
        "mute.invalid_rule": "Выбрано недействительное правило.",
        "mute.role_not_configured": "Роль мута не настроена. Используйте `/moderation settings moderation_set_mute_role` или `/moderation settings moderation_create_mute_role`.",
        "mute.role_missing": "Настроенная роль мута отсутствует на сервере. Настройте её заново.",
        "mute.role_too_high": "Я не могу выдать эту роль мута, потому что она выше или равна моей верхней роли.",
        "mute.duration_exceeds": "Длительность превышает максимум для сервера ({max_minutes} минут).",
        "mute.assign_forbidden": "У меня нет прав выдать роль мута.",
        "mute.assign_failed": "Не удалось выдать роль мута: {error}",
        "mute.reconnect_ok": " Переподключение в войсе выполнено.",
        "mute.reconnect_failed": " Не удалось переподключить пользователя в войсе (проверьте права на перемещение).",
        "mute.log_failed": "Пользователь замучен, но не удалось сохранить действие: {error}",
        "mute.success": "{mention} получил мут на `{duration}` минут по правилу `{rule}`.{note}",
        "unmute.remove_forbidden": "У меня нет прав снять роль мута.",
        "unmute.remove_failed": "Не удалось снять роль мута: {error}",
        "unmute.success": "{mention} размучен. Роль снята: `{removed_role}`. Закрыто активных мутов: `{deactivated}`.",
        "settings.language_updated": "Язык сервера обновлён: `{locale}`.",
        "settings.language_not_supported": "Неподдерживаемый язык. Доступные: {supported}.",
    },
}
