apiVersion: v1
kind: Secret
metadata:
  name: cybercolors-app-secrets
  namespace: cybercolors
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: ""
  TEST_GUILD_ID: ""
  DISCORD_CLIENT_ID: ""
  DISCORD_TEST_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  DISCORD_REDIRECT_URI: "https://cybercolors.lightny.pro/"
  OPENAI_API_KEY: ""
  OPENAI_ORG: ""
  MODAL_TOKEN_ID: ""
  MODAL_TOKEN_SECRET: ""
  TIMEZONEDB_KEY: ""
