import sqlalchemy as sa
import sqlmodel
from alembic import op

"""added avatar hash

Revision ID: 1c15ef3763a8
Revises: 7aec09e2ff3f
Create Date: 2025-10-15 13:07:13.671039

"""


# revision identifiers, used by Alembic.
revision = '1c15ef3763a8'
down_revision = '7aec09e2ff3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_users', sa.Column('avatar_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_users', 'avatar_hash')
    # ### end Alembic commands ###
