import sqlalchemy as sa
import sqlmodel

from alembic import op

"""Fix dametime in joined at

Revision ID: 7aec09e2ff3f
Revises: b94fb227a27b
Create Date: 2025-10-14 21:40:36.962523

"""


# revision identifiers, used by Alembic.
revision = '7aec09e2ff3f'
down_revision = 'b94fb227a27b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_users', 'joined_discord',
               existing_type=sa.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('global_users', 'joined_discord',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
