import sqlalchemy as sa
import sqlmodel
from alembic import op

"""added server icon

Revision ID: f28c810a6583
Revises: 1c15ef3763a8
Create Date: 2025-10-15 16:18:36.891075

"""


# revision identifiers, used by Alembic.
revision = 'f28c810a6583'
down_revision = '1c15ef3763a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'icon')
    # ### end Alembic commands ###
