import sqlalchemy as sa
import sqlmodel
from alembic import op

"""removed redundant messages tabl

Revision ID: messages_removed
Revises: replies_index_fix
Create Date: 2026-02-05 10:47:26.866411

"""


# revision identifiers, used by Alembic.
revision = 'messages_removed'
down_revision = 'replies_index_fix'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_phrase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('respond_phrase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('added_by_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], name=op.f('messages_server_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('messages_pkey'))
    )
    # ### end Alembic commands ###
