import sqlalchemy as sa
import sqlmodel
from alembic import op

"""moved the index to bot reply

Revision ID: replies_index_fix
Revises: replies_added
Create Date: 2026-02-04 11:15:20.720761

"""


# revision identifiers, used by Alembic.
revision = 'replies_index_fix'
down_revision = 'replies_added'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_user_message'), table_name='replies')
    op.create_index(op.f('ix_replies_bot_reply'), 'replies', ['bot_reply'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_bot_reply'), table_name='replies')
    op.create_index(op.f('ix_replies_user_message'), 'replies', ['user_message'], unique=False)
    # ### end Alembic commands ###
