import sqlalchemy as sa
import sqlmodel
from alembic import op

"""added a replies table

Revision ID: replies_added
Revises: f28c810a6583
Create Date: 2026-02-04 11:13:37.014942

"""


# revision identifiers, used by Alembic.
revision = 'replies_added'
down_revision = 'f28c810a6583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bot_reply', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['global_users.discord_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_user_message'), 'replies', ['user_message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_user_message'), table_name='replies')
    op.drop_table('replies')
    # ### end Alembic commands ###
