apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - datasource.yaml
  - grafana-pvc.yaml
configMapGenerator:
  - name: grafana-observability-dashboards
    files:
      - dashboards/cybercolors-logs.json
      - dashboards/cluster-log-overview.json
      - dashboards/platform-overview.json
      - dashboards/cybercolors-runtime.json
      - dashboards/observability-health.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
