apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-registry
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: ext4
  dataLocality: best-effort
  unmapMarkSnapChainRemoved: enabled
  disableRevisionCounter: "true"
  dataEngine: v1
  backupTargetName: default
  nodeSelector: registry-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-claim-longhorn-v2
  namespace: container-registry
  annotations:
    cybercolors.dev/migration-status: active
  labels:
    migration.cybercolors.dev/source: registry-claim-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-registry
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
